version: '3.3'

services:

  menu3-db:
    container_name: menu3-db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: menu3
      MYSQL_PASSWORD: root

  menu3-api:
    container_name: menu3-api
    image: menu3/api
    depends_on:
      - menu3-db
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: menu3-db
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: menu3
      DATABASE_PORT: 3306